version: '3'
services:
  mongo:
    image: mongo:8
    container_name: mongo-database
    ports:
      - "27017:27017"
    networks:
      - db-optimization
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          memory: "2G" 

  express-server:
    build: ./
    container_name: express-server
    ports:
      - '3000:3000'
    networks:
      - db-optimization
    depends_on:
      mongo: 
        condition: service_started
    environment:
      - MONGO_URL=mongodb://mongo:27017/db_optimization

networks:
  db-optimization:
    driver: bridge

volumes:
  mongo_data: